steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/gcpdevops-495507/python-repo/runimage:v1',
      '.'
    ]

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'us-central1-docker.pkg.dev/gcpdevops-495507/python-repo/runimage:v1'
    ]

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    [
      'run',
      'deploy',
      'runwithcicd',
      '--image',
      'us-central1-docker.pkg.dev/gcpdevops-495507/python-repo/runimage:v1',
      '--region',
      'us-central1',
      '--allow-unauthenticated'
    ]

images:
- 'us-central1-docker.pkg.dev/gcpdevops-495507/python-repo/runimage:v1'
